namespace Crypto;

public static class FileStorageXORCipher
{
    public static byte[] Cipher(byte[] file, byte[] key) // 128-byte key generated by resourceName
    {
        var result = new byte[file.Length];
        for (int i = 0; i < file.Length; i++)
            result[i] = (byte)(file[i] ^ key[i % key.Length]);
        return result;
    }
}